apiVersion: v1
kind: Service
metadata:
  name: tools-kafka-service
  labels:
    app: tools-kafka
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 18080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tools-kafka
  externalIPs:
    - 127.0.0.1
